x=2;
y=3.5;
z=7;
s1="Campanha Avon";
s2=" do ";
s3="JavaScript";
s=s1+s2+s3;                 // concatenação de strings
soma=x+y;                   // adição
mult=x*y;                   // multiplicação
div=x/y;                    // divisão
sub=x-y;                    // subtracção
mod=x%y;
pontos = 100; 
nome ="Fulano de Tal"                   // resto da divisão inteira
